version: '3'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5433:5432
    expose:
      - 5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    expose:
      - 3000
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: > 
      bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh -t 25 postgres:5432
      && rails db:reset && rails server --binding 0.0.0.0 --port 3000"

  frontend:
    container_name: front
    image: node:12.14.0-stretch
    expose:
      - 8084
    ports:
      - 8084:8084
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh -t 25 backend:3000
      && npm install yarn && cd omdb-react && yarn install && yarn start"
    depends_on:
      - backend