version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: > 
      bash -c "rails server --binding 0.0.0.0 --port 3000"